// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPpfqaNBGVvk5IFytn7IccCdmKb--jFa4',
    appId: '1:909102038701:web:e33021edccede46334d024',
    messagingSenderId: '909102038701',
    projectId: 'finans-fc0e8',
    authDomain: 'finans-fc0e8.firebaseapp.com',
    databaseURL: 'https://finans-fc0e8-default-rtdb.firebaseio.com',
    storageBucket: 'finans-fc0e8.appspot.com',
    measurementId: 'G-JM1PKKTNM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJcuwsTjSUNAJ7CbDJqH7WhoGM7QsIhrU',
    appId: '1:909102038701:android:f39202c541b0b55034d024',
    messagingSenderId: '909102038701',
    projectId: 'finans-fc0e8',
    databaseURL: 'https://finans-fc0e8-default-rtdb.firebaseio.com',
    storageBucket: 'finans-fc0e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcSgLgUSSyXjSMQlI1j-vJ-gxi3_MoaPk',
    appId: '1:909102038701:ios:5e12caeb1aebc08134d024',
    messagingSenderId: '909102038701',
    projectId: 'finans-fc0e8',
    databaseURL: 'https://finans-fc0e8-default-rtdb.firebaseio.com',
    storageBucket: 'finans-fc0e8.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcSgLgUSSyXjSMQlI1j-vJ-gxi3_MoaPk',
    appId: '1:909102038701:ios:1a4af914d8e751fc34d024',
    messagingSenderId: '909102038701',
    projectId: 'finans-fc0e8',
    databaseURL: 'https://finans-fc0e8-default-rtdb.firebaseio.com',
    storageBucket: 'finans-fc0e8.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
